directories:
  output: release
  buildResources: build
appId: com.kstech.bukharilab
productName: Bukhari Lab
copyright: Copyright © 2026 KS Tech
files:
  - filter:
      - dist/**/*
      - electron/**/*
      - node_modules/**/*
      - package.json
extraResources:
  - from: src/assets
    to: assets
    filter:
      - '**/*'
win:
  target:
    - target: nsis
      arch:
        - x64
  icon: public/icon.ico
  requestedExecutionLevel: asInvoker
nsis:
  oneClick: false
  allowToChangeInstallationDirectory: true
  createDesktopShortcut: true
  createStartMenuShortcut: true
  shortcutName: Bukhari Lab
  installerIcon: public/icon.ico
  uninstallerIcon: public/icon.ico
  installerHeaderIcon: public/icon.ico
  deleteAppDataOnUninstall: false
  include: scripts/installer.nsh
electronVersion: 40.8.2
